/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as directGrantsSimple from "./direct-grants-simple";
export type { directGrantsSimple };
export type { BaseStrategy } from "./BaseStrategy";
